class GenericConstants:
    RAW_DATA = 'raw'
    PROCESSED_DATA = 'processed'
    CURRENT_ENV = 'current_environment'
    DEV_ENV = 'dev_mac'
    PROD_ENV = 'prod_env'
    LIVIS = 'livis'


class DBConstants:
    pre = ''
    IMG_FNAME = pre + 'image_filename'
    IMG_ID = pre + 'image_id'
    IMG_TSTAMP = pre + 'image_timestamp'
    ORIENT = pre + 'orientation'
    MJR_LEN = pre + 'major_length'
    MIN_LEN = pre + 'minor_length'
    MODEL_NAME = pre + 'model_name'
    USR_LBL = pre + 'user_labels'
    PRED = pre + 'pred'
    PROB = pre + 'prob'
    PRED_TSTAMP = pre + 'pred_timestamp'
    ML_LBL = 'machine_label'
    HMN_LBL = 'human_label'
    IMG_STATUS = 'image_status'
    HEIGHT = pre + 'height'
    WIDTH = pre + 'width'
