#!/usr/bin/env bash

# This is the set of commands to execute on the local machine for:
# 1. Transfer the .tif images from the local machine to a folder in SVCL server
# 2. Convert the .tif files into jpeg (into the preferred input type of the classifier) using spcconvert
# 3. Deploy the classifier and Obtain the predictions
# 4. Send the predictions back to SIO server


#*********************************

# Step 1
# We transfer the images on the local machine to the SVCL Server using scp command
# Change the paths accordingly:

#source_path="/Users/snehakondur/Downloads/IMAGES"
#ssh_key="sneha@gpu6"
svcl_dir="/data6/SnehaKondur/hab-spc/LIVIS"
#dest_path="$ssh_key:$svcl_dir"

#scp -r $source_path $dest_path

#*********************************

# Step 2
# Using SPC Convert

ssh sneha@gpu6 "cd /data6/SnehaKondur/hab-spc/LIVIS/SPCConvert/; python spcconvert.py /data6/SnehaKondur/hab-spc/LIVIS/IMAGES"

